name: Log Issue Events
on:
  issues:
    types: [opened, edited]
jobs:
  log-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue event details
        run: echo "${{ toJson(github) }}"
